import type { Metadata } from "next";
import '@/style/global.css'
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: {default: "NeuroLife - AI Daily Journal", template : "%s | NeuroLife"} ,
  
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       
      >

         <SidebarProvider>
          <AppSidebar />.
<div  className="flex min-h-screen w-full flex-col">

          <Header/>
  
          <main className="flex flex-1 flex-col px-4 pt-10  xl:px-8">
        {children}
          </main>
</div>
        </SidebarProvider>
      </body>
    </html>
  );
}
