import type { Metadata } from "next";
import '@/style/global.css'
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSideBar from "@/components/MyAppSidebar";
import Header from "@/components/Header";
import { ThemeProvider } from "@/components/providers/themeProvider";
import { Toaster } from "react-hot-toast";
import NoteProvider from "@/components/providers/NoteProvider";

export const metadata: Metadata = {
  title: {default: "NeuroLife - AI Daily Journal", template : "%s | NeuroLife"} ,
  
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
       
      >

        <ThemeProvider
        attribute="class"
        defaultTheme="dark"
  enableSystem
        disableTransitionOnChange

      
        >
<NoteProvider>
         <SidebarProvider>
          <AppSideBar />
<div  className="flex min-h-screen w-full flex-col">

          <Header/>
  
          <main className="flex flex-1 flex-col px-4 pt-10  xl:px-8">
        {children}

        <Toaster
        position="bottom-right"
        toastOptions={{
          duration: 4000,
          style : {
            padding: '12px 16px',
            borderRadius : '8px',
            fontSize : '14px'
          }
        }}
        />
          </main>
</div>
        </SidebarProvider>
        </NoteProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
